export enum RhythmState {
  NOT_STARTED = 'NOT_STARTED',
  OFF_RHYTHM = 'OFF_RHYTHM',
  STARTING_TO_FLOW = 'STARTING_TO_FLOW',
  ON_CADENCE = 'ON_CADENCE',
  FLOWING_IN_RHYTHM = 'FLOWING_IN_RHYTHM',
}